mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

handler404 = "mysite.views.page_not_found_view"

polls/urls.py
from django.urls import path, re_path

from . import views

app_name = 'polls'
urlpatterns = [
    # example: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # example: /polls/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # example: /polls/5/results
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # example: /polls/5/vote
    path('<int:question_id>/vote', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently'
    )
    def was_published_recently(self):
        now = timezone.now()  # UTC time
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/views.py
from django.shortcuts import render
def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

from django.utils import timezone

import random


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be published in the future).
        """
        return Question.objects.exclude(choice__isnull=True
                                        ).filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.exclude(choice__isnull=True).filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.exclude(choice__isnull=True).filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {
                          'question': question,
                          'error_message': "You didn't select a choice.",
                      })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/main.css' %}">

        {% block style %}{% endblock %}
        {% block title %}<title>Base</title>{% endblock %}
    </head>

    <body>
        {% block content %}{% endblock %}

        <ul class="contact-block">
            <li class="contact-item">
                <a href="https://github.com/quaismodo" class="github-link">
                    <img src="{% static 'polls/img/github-logo.svg' %}" alt="" width="50"></a>
            </li>
            <li class="contact-item">
                <a href="https://t.me/quaismodo" class="telegram-link">
                    <img src="{% static 'polls/img/telegram-logo.svg' %}" alt="" width="50"></a>
            </li>
        </ul>
    </body>

</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'polls/detail.css' %}">
{% endblock %}

{% block title %}<title>{{ question.question_text }}</title>{% endblock %}

{% block content %}
<main class="container">
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}

        <fieldset>
            <legend class="title-contain">
                <h1 class="title">{{ question.question_text }}</h1>
            </legend>

            {% if error_message %}
            <span class="error-tag">{{ error_message }}</span>
            {% endif %}

            <ul class="inputs-list">
                {% for choice in question.choice_set.all %}
                <li>
                    <input class="radio" type="radio" name="choice" id="choice{{ forloop.counter }}"
                           value="{{ choice.id }}">
                    <label class="radio-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>

                </li>
                {% endfor %}
            </ul>
        </fieldset>
        <input class="button" type="submit" value="Vote">
    </form>

</main>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'polls/index.css' %}">
{% endblock %}
{% block title %}<title>Question</title>{% endblock %}



{% block content %}
    <main class="container">
        <div class="title-wrapper">
            <h1 class="title">Questions</h1>
            <span class="question-counter">{{ latest_question_list.all.count }}</span>
        </div>

        {% if latest_question_list %}
        <ul class="list">
            {% for question in latest_question_list %}
            <li  class="list-item"><a href="{% url 'polls:detail' question.id %}" class="item-link">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p class="other">No polls are available.</p>
        {% endif %}

    </main>
{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'polls/results.css' %}">
{% endblock %}

{% block title %}<title>{{ question.question_text }} Result</title>{% endblock %}

{% block content %}

<main class="container">
    <div class="title-wrapper">
    <span class="subtitle">Results</span>
    <h1 class="title">{{ question.question_text }}</h1>
        </div>



    <ul class="list">
        {% for choice in question.choice_set.all %}
        <li class="list-item"><span class="choice-text">{{ choice.choice_text }}</span>
            <span class="count-vote">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
        {% endfor %}
        <a class="vote-link" href="{% url 'polls:detail' question.pk %}">Vote again</a>
        <a class="vote-link" href="{% url 'polls:index' %}">Back to questions</a>
    </ul>



</main>

{% endblock %}